/**
 * Compile-time guard that `en.ts` and `pt.ts` hold exactly the same keys.
 *
 * Why this file exists: `t()` returns the key itself when a lookup misses, so a
 * key added to one dictionary and forgotten in the other does not throw, does
 * not warn, and does not fall back — it renders the raw key on screen for every
 * user of that language. That failure is invisible in review and invisible in
 * the build, which is exactly the combination that lets it ship.
 *
 * Both imports are `import type`, so they are erased at compile time. This file
 * adds nothing to any bundle, and in particular it does NOT pull `en` into the
 * initial chunk — `en` stays code-split and lazily loaded, which is the whole
 * point of the arrangement in `useTranslation.ts`.
 *
 * If you see a TypeScript error pointing here, do not edit this file. Read the
 * error: the offending key names are printed in it. Add them to whichever
 * dictionary is missing them.
 */
import type en from "./en";
import type pt from "./pt";

type OnlyInEn = Exclude<keyof typeof en, keyof typeof pt>;
type OnlyInPt = Exclude<keyof typeof pt, keyof typeof en>;

/**
 * Resolves only when `T` is `never`. When the dictionaries diverge, `T` is the
 * union of the offending key names, and the compiler names them in the error.
 */
type AssertNoStrayKeys<T extends never> = T;

export type EnHasNoKeysMissingFromPt = AssertNoStrayKeys<OnlyInEn>;
export type PtHasNoKeysMissingFromEn = AssertNoStrayKeys<OnlyInPt>;
